# Generated by Django 5.1.7 on 2025-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_per_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='production_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='batch_packages',
            field=models.IntegerField(default=0),
        ),
    ]
