# Generated by Django 5.1.7 on 2025-04-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_batch_per_days_product_production_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='batch_packages',
            new_name='daily_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='batch_per_days',
        ),
        migrations.AddField(
            model_name='product',
            name='max_orders',
            field=models.IntegerField(default=1),
        ),
    ]
