# Generated by Django 5.1.7 on 2025-04-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_batch_packages_product_daily_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_orders',
            new_name='max_orders_day',
        ),
    ]
