# Generated by Django 5.1.7 on 2025-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_max_orders_product_max_orders_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='daily_capacity',
            new_name='batch_packages',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='max_orders_day',
            new_name='batch_production_days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='production_days',
        ),
        migrations.AddField(
            model_name='product',
            name='daily_batch_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
