# Generated by Django 5.1.7 on 2025-04-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethod',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='OrderStatus',
            new_name='Status',
        ),
    ]
