# Generated by Django 5.1.7 on 2025-05-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='identifier',
            field=models.IntegerField(default=0),
        ),
    ]
