# Generated by Django 5.1.7 on 2025-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_status_identifier'),
        ('products', '0006_alter_product_batch_packages_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productorder',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_product_per_order'),
        ),
    ]
