# Generated by Django 5.1.7 on 2025-05-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productorder_unique_product_per_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
