# Generated by Django 5.1.7 on 2025-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_productorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
