# Generated by Django 5.1.7 on 2025-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_productorder_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
