# Generated by Django 5.1.7 on 2025-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_productorder_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_due_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
