# Generated by Django 5.1.7 on 2025-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_payment_due_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
