# Generated by Django 5.1.7 on 2025-04-09 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_contact_delete_customercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8)),
                ('street_name', models.CharField(max_length=90)),
                ('district', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=2)),
                ('observation', models.CharField(max_length=100)),
                ('is_billing_address', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customers.customer')),
            ],
        ),
    ]
