# Generated by Django 5.1.7 on 2025-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='observation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
