# Generated by Django 5.1.7 on 2025-04-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='owner',
            new_name='created_by',
        ),
    ]
