# Generated by Django 5.1.7 on 2025-05-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_rename_owner_customer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
