# Generated by Django 5.1.7 on 2025-03-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
