# Generated by Django 5.1.7 on 2025-04-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuserinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuserinvitation',
            old_name='expires_at',
            new_name='expire_at',
        ),
    ]
