# Generated by Django 5.1.7 on 2025-04-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_productionschedule'),
        ('products', '0002_product_batch_per_days_product_production_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionschedule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_schedule', to='products.product'),
        ),
    ]
