# Generated by Django 5.1.7 on 2025-04-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_productionschedule_product'),
        ('orders', '0003_order_created_by'),
        ('products', '0004_rename_max_orders_product_max_orders_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='productionschedule',
            options={'ordering': ['production_date']},
        ),
        migrations.RenameField(
            model_name='productionschedule',
            old_name='date',
            new_name='production_date',
        ),
        migrations.RenameField(
            model_name='productionschedule',
            old_name='batches',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='production_order', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='productionschedule',
            unique_together={('product', 'order', 'production_date')},
        ),
    ]
