# Generated by Django 5.1.7 on 2025-04-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionschedule',
            old_name='quantity',
            new_name='amount',
        ),
    ]
