# Generated by Django 5.1.7 on 2025-05-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_rename_quantity_productionschedule_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionschedule',
            old_name='amount',
            new_name='batches',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
