# Generated by Django 5.1.7 on 2025-05-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_rename_amount_productionschedule_batches_and_more'),
        ('products', '0006_alter_product_batch_packages_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productionschedule',
            unique_together={('product', 'production_date')},
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='order',
        ),
    ]
