# Generated by Django 5.1.7 on 2025-05-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_productionschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionschedule',
            name='packages',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
