# Generated by Django 5.1.7 on 2025-06-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_productionschedule_packages'),
        ('orders', '0012_order_payment_due_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionschedule',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_production', to='orders.order'),
            preserve_default=False,
        ),
    ]
