name: FamiliarHub Production Deploy

on:
  pull_request:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}
      
      - name: Deploy to Production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'ENDSSH'
            source venv/bin/activate
            cd FamiliarHub/
            git pull origin master
            export DJANGO_ENV=prod
            pip install -r requirements.txt
            python manage.py migrate
            sudo /usr/bin/systemctl restart ${{ secrets.DROPLET_SERVER }}
          ENDSSH